apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: nats-pubsub
  namespace: default
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
    - name: natsURL
      value: "nats://localhost:4222"
    - name: name
      value: "mynats"
    - name: maxReconnect
      value: "10"
    - name: reconnectWait
      value: "2s"
    - name: durable
      value: "true"
    - name: queueGroup
      value: "mygroup"
